[project]
name = "fastapi-rpa-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.124.4",
    "playwright>=1.57.0",
    "uvicorn>=0.38.0",
    "sqlalchemy>=2.0.3",
    "pymysql>=1.0.2"
]
